### ISSUE TITLE
Fee.linear_fee in node is not  useful

### ISSUE THREAD

**Issue by lvshaoping007** [SebastienGllmt/js-chain-libs-node-pkg#1]
i try use Fee.linear_fee in node . but not useful 
`
let fee0 = RustModule.WalletV3.Value.from_str('200000');
let fee1 = RustModule.WalletV3.Value.from_str('100000');
let fee2 = RustModule.WalletV3.Value.from_str('400000');
const feeAlgorithm = RustModule.WalletV3.Fee.linear_fee(fee0,fee1,fee2);
`

when run 4th row ,will throw Error: expected instance of PerCertificateFee

Can you help me? 
thank you very much

**Comment by SebastienGllmt** [comment]
You need to specify the per-certificate fee also
https://github.com/Emurgo/yoroi-frontend/blob/shelley/app/api/ada/transactions/shelley/utils.js#L197
